### ISSUE TITLE
Thumbnail images aren't being replaced with original

### ISSUE THREAD

**Issue by Kagukara** [ppixiv/ppixiv#107]
As I understand, the section in this code should replace the thumbnail url image with the original images url. https://github.com/ppixiv/ppixiv/blob/2bb79583343d530333c4d9645f04ab7a73793f0d/web/vview/misc/guess-image-url.js#L180

This is not happening for me, the thumbnails still use the `/img-master/` format instead of the `/img-original/` format.

**Comment by ppixiv** [comment]
GuessImageURL guesses the full image URL from other images that it's seen by an author.  Search APIs don't include the full URL, but if a user posts mostly JPEGs, we'll guess that the URL will be a JPEG.  It's only used for image preloading, to try to begin preloading sooner so it's more likely to be ready in time.  But it won't always work, since it's just a guess.  Besides, trying to use full images as thumbnails wouldn't work well since there might be hundreds of MB of images in a single screen of thumbnails (Pixiv allows images up to 32MB each).

Thumbnails use the highest-res regular thumbnail available (see vview/util/getHighResThumbnailUrl).  It would be nice if there was a higher-res WebP version for viewing with very large thumbs, but Pixiv is probably slow to add more thumbnail variants that they'd have to create for a hundred million images...

**Comment by Kagukara** [comment]
Ah, I see. I'll close this issue as it ls a limitation of pixiv and not possible at the moment for ppixiv.
