### ISSUE TITLE
Loading a search/gallery starting at a specific page

### ISSUE THREAD

**Issue by scrumpyman** [ppixiv/ppixiv#11]
After using this plugin for a while now, this is my most wanted feature left (and almost the only one!)

Whether I'm going through an artist, a tag, or new works by following, I often want to come back to where I left off later, and this doesn't seem to be possible right now without scrolling down a whole lot and loading every thumbnail along the way.

Even without that scenario, it would also be nice if going to search from any image could load the artist's gallery to that specific image.

If I were to lazily implement this myself I would queue up some scrolling and page loads until the specific page or image is reached, but ideally the gallery mode would be able start on a particular page, with a separator between thumbnails indicating the page numbers, and a button to go back to the first page.

**Comment by ppixiv** [comment]
The current version does this for bookmarks.  I don't know if I'll add it for other searches, it only actually works well on searches that don't change very much.  It's particularly useful for bookmarks, I have thousands of bookmarks and there was really no way to browse the older ones before.  I'll think about other searches later, I want to let what's in there bake for a while.

We can't go to a specific image since there's no way of knowing which page in the results it would be on, and I want to be sure never to spam API requests.  It's rude to the site, and people could end up getting blocked if they unknowingly do something that causes hundreds of search pages to be loaded rapid fire.

It would be sort-of possible to do it with the userIllusts list that appears in the illust page, which is a list of all of the user's post IDs.  That's really limited, though (you could guess at the page number for the base search, but not if any search options are enabled), and I don't really want to rely on that list, since that's the only place it appears and it seems like something that might be removed some day.

**Comment by scrumpyman** [comment]
I think the implementation on the bookmark gallery would work well on all of them. I don't see a scenario where loading a gallery with a page count where you wouldn't want to load to that page, and if the results are different, the page you want would always be further ahead so it always saves some scrolling and api calls.

The only quirk with the bookmark page is that there doesn't seem to be any way to go back directly to page 1 without opening a new tab, even if you load a different search and come back it stays there (I'm guessing the gallery is not unloaded)

Standard pagination buttons that unload the gallery then load any page would be great too.

I personally would find it strange if they removed the artist illust list since I find it so useful, but I guess that wouldn't be a first. Pretty much the only case (other than going on the front page) where I go out of ppixiv now is to check how far in I am when going through an artist. Speaking of which, an indication like "page 5/12" or so on gallery view would be another great addition.

**Comment by puyebu** [comment]
I would like to request the same. I have recently found the script and found it very useful.

However, I frequently use large searches for 10k images or more and continuous load without ability to load search on a specific page or unload previous results is not very comfortable.

As of now I browse by year by manually editing &scd=2000-01-01&ecd=2001-01-01 params.
It would be fine for me if I could load &p=25 and continue browsing from that specific page without going to a specific image.

**Comment by ppixiv** [comment]
Sorry for the reply a million years later, trying to clean up old tickets that I've rudely left behind for a long time.

Newer versions support resuming pages on the searches where it makes sense, including tag searches and the followed users page, and you can refresh searches at the current page or refresh back at the top.  I don't think I want to show pages directly in the UI or set the page directly since it doesn't fit very well (it's meant to be a seamless flow of results, mostly hiding the underlying pages), but you can see which page you're actually on by looking at the URL, which updates dynamically as you scroll down, and you can edit that directly if you want to jump to a specific page.

Scrolling to the artist doesn't fit easily into the current search interface, it would need to adjust the page number in the address bar once it knows what page the post it's trying to scroll to is on.  It'd probably complicate things too much.
