### ISSUE TITLE
Suggestion: Image viewer doesn't open on images but on list

### ISSUE THREAD

**Issue by Felina-Lain** [ppixiv/ppixiv#12]
I just discovered this, and it's a life saviour for exploring pixiv, 

If I were to make a suggestion though:
when I open an image collection, I'd love it if it gave me the image list/grid first, and then allowed me to open whichever image I want full window, and navigate with scroll from there

Is there a way to make grid the default?

**Comment by ppixiv** [comment]
If you're coming from site searches that's tricky to do, since the UI decides what to display before it knows what type of image it is.  If you use the built-in search interface it'll go to the page list first, though.  It's meant to let you do all of your searching and browsing without having to exit into Pixiv and things are much faster that way, but I don't know how other people actually use it...

**Comment by Felina-Lain** [comment]
> If you're coming from site searches that's tricky to do, since the UI decides what to display before it knows what type of image it is. If you use the built-in search interface it'll go to the page list first, though. It's meant to let you do all of your searching and browsing without having to exit into Pixiv and things are much faster that way, but I don't know how other people actually use it...

Well it wasn't doing it at first, I used the ppixiv built-in search, and it would autozoom, but then this morning it started doing it right, so maybe some other plugin I had was messing with it

thanks anyway for the amazing plugin!
