### ISSUE TITLE
Image change with scrolling right after loading or refreshing an artwork page

### ISSUE THREAD

**Issue by scrumpyman** [ppixiv/ppixiv#15]
Right now when the mouse scroll is used to change image after loading a fresh artwork page (which is easy to do accidentally too), the script loads the newest image by the same artist, and the address is changed without adding the previous page to the browser history, thus losing the first loaded page.

I feel like this was handled better before the switch to the new urls, but I could be remembering wrong. In any case, the script should at least add the page to the browser history (maybe even for every time the artwork is changed in general). If that's not possible somehow, block page up or down switches when there isn't a known image to switch to. Ideally the script would find the next and previous images of the artist when loading any artwork link, though.

**Comment by ppixiv** [comment]
Sorry, don't think I saw this.  It intentionally doesn't add to history when switching between images, because that spams history and really just makes it unusable.  I typically click an image in a search, mousewheel around for a while, then hit browser back to go back to the search, and you might have to go back dozens of times if every individual image switch was pushed onto history.

If you load an illustration page directly, it treats it as if you're viewing it from the artist's post list, since it needs to assign a source for it.  It's just a fallback, though, and doesn't always know where the post really is in the list, so if you navigate to the next image and it can't find where you are, it falls back on the first image.  I don't know if I want to complicate things around that, but if you describe how you're using the UI to see that a lot I can at least look at it.  Is it just from middle-clicking images in searches?

**Comment by ppixiv** [comment]
Newer versions use a separate data source when loaded directly to an image that doesn't use the artist's post list, which doesn't navigate to other posts.  Instead, it redirects to the artist's post list if you navigate out in the popup menu, but the illust page itself is isolated.  This is related to some  unrelated features and the "don't know where to go so going to the first image" fallback is still there for other pages, but I think the particular problem you were running into shouldn't happen.  Closing this, but if you're still having trouble (a year and a half later, sorry :) feel free to reopen or open another ticket.
