### ISSUE TITLE
Feature: Image scrolling using scroll wheel

### ISSUE THREAD

**Issue by Jack21345** [ppixiv/ppixiv#18]
Hi, I find your script to be damn near perfect for my needs, yet there is one thing that could really be implemented. 

Basic image scrolling using mouse wheel. At the moment, whenever I use scale with filling I, luckily, manage to make it fit by width.
Thing is, one would expect to use the scroll wheel to view the image, yet it starts going for the next or previous image from the get go. What's even more funny is that _dragging_ actually works so we have people dragging images one after another instead of using a wheel. 

I suggest enabling scrolling with toggling prev-next image upon reaching bottom or top borders. Making a 1-2 scroll pause before changing the image to prevent misclicks would be really great too. 
If an image is not overflown, then no scrolling kicks off and we switch image like before. 

Would honestly really appreciate this function.

Cheers.

**Comment by ppixiv** [comment]
Sorry for never getting back on this.  I did experiment with it.  It makes it hard to quickly navigate between images, since you have to scroll all the way to the bottom (or back to the top) first, and it only really works when in cover mode (when you can only zoom one way).  I might keep playing around with it, but I think it needs too much different behavior to fit with the rest of the UI.
