### ISSUE TITLE
Bug: Popularity toggle

### ISSUE THREAD

**Issue by jollld** [ppixiv/ppixiv#19]
Hello there, really enjoy this script, of all i've found for pixiv it's honestly the best in improving user experience!

However there is a bug that is really annoying me, for example when i search any tag, clicking the popularity toggle doesn't do anything other than sorting the pics by date uploaded.

![2021-03-17 15_31_36-Search_ Kagura (Gintama) and 13 more pages - Personal - Microsoft​ Edge](https://user-images.githubusercontent.com/72407660/111493966-f77b4700-8735-11eb-98df-f07d89409d52.jpg)

Could you please fix this bug?
Or if you would rather not because of the issue with pixiv premium, then could you make the script cooperate with https://greasyfork.org/en/scripts/30766-pixiv-previewer , sorting function?

**Comment by ppixiv** [comment]
Popularity sorts are a Premium feature, it's disabled by the site if you don't have it.  All you can sort by without premium is newest and oldest images.

That script only sorts results within the first page or two, since there's no way to sort all results when you can only see a page at a time.  I don't think sorting individual pages is too useful (the idea is to show popular images of all time, or in the last year, not just in the last page), and it'd be extra confusing since we don't show results in pages.  This is something that really needs to be done by the server to work properly.
