### ISSUE TITLE
A few changes I made that you could implement

### ISSUE THREAD

**Issue by scrumpyman** [ppixiv/ppixiv#2]
Hey, I quite like your script, and I have been making some changes, so I figured it'd be good to share. Some are personal and should be made into options, others are definitive improvements. Modified script is linked (use diff checker to see changes). Tested on tampermonkey in firefox and chrome.

Improvements and fixes:
- Added download button to right click menu
- Added referer to download_urls request, fixes random 403 errors in firefox and enables download from right click menu in gallery or thumbnail mode
- Fixed the image disappearing when opening the right click menu while image is zoomed (might have been a browser issue, fixed by opening the normal ui for 10ms)

Changes that should be options:
- Download gives a single image of the current manga page (zip could be another button)
- Download auto bookmarks illust
- Inversed dragging axis
- Opening right click menu while zoom-dragging sets zoom lock to true, a nice way to quickly set a zoomed view
- Changing zoom level doesn't set zoom lock to true
- Different naming style for downloads
- Disable cursor hiding

Things I would like but didn't bother adding:
- More information displayed in gallery mode and on context menu, like date, image filetype, and filesize
- Set filesize treshold to download preview image instead of original when it's absurdly huge
- Thumbnail panel for manga illust view displayed on the side in a vertical scroll, similar to e-hentai multi page viewer

[ppixiv.zip](https://github.com/ppixiv/ppixiv/files/3618179/ppixiv.zip)

**Comment by monater** [comment]
How to solve the problem that the settings box takes up too much space
![问题_LI](https://user-images.githubusercontent.com/55580338/65314713-6f13f880-dbc9-11e9-8ee4-f26afe10de0e.jpg)

**Comment by ppixiv** [comment]
@monater It's better to ask questions in a separate ticket than to comment on someone elses.  Are you in a very small window?  I can try making it so the search box can collapse, but it works best in a maximized window.

@scrumpyman It'll take a bit to look at these.  I haven't seen the image disappearing, where were you seeing that?  I'd like to track it down a bit more (having a 10ms timer could cause race conditions).

For GM_download, is there a case where the blob download isn't working?  I try to avoid changing grants, since it'll trigger a permission prompt for everybody when it updates.

**Comment by monater** [comment]
@ppixiv I am sorry,and I will pay a attention to this.I quite need the collapse,because I am in a small window.
by the way, my English is poor, please don't mind. ＞︿＜

**Comment by ppixiv** [comment]
@monater Try updating, and enable "Hover to show UI".

**Comment by scrumpyman** [comment]
The issue with the image disappearing happens whenever the image is on zoom lock, at any level, and the right click menu is opened. The image disappears until something else shows up on top of it, even another program window will do. Only on firefox (I'm on latest update). So it's probably some hardware acceleration / hardware / browser issue. Havent seen anything else similar happen though.

My issue with blob downloads is that they freeze the tab for a few seconds, and can't be automatically saved without prompt. I've added a gm_download method that can save to a folder inside Downloads without any prompt or freezes which is much quicker, but there's also some issues with that. In firefox only, adding referrers seems to break the download entirely, and in chrome, the folder slashes get replaced by underscores. So it's only useful on firefox when on illust pages. Quite a mess.

Also, I hope pixiv doesn't mess with the urls again. I'll have to keep updating my changed script since there's now too many personal changes to hope for a merge.

Speaking of one of those changes though, I saw that you had a disabled thumbnail display at the bottom. I've made it vertical and permanently visible to the side, it works great. Should definitely be added back in. With maybe a scrollbar on it to load a page near the end without preloading 50 pages which slows down things a lot.

**Comment by ppixiv** [comment]
Using lower-resolution images doesn't work too well, since they don't create very usable downscales.  They just have "regular", which I think is capped at 1200 in each direction (way too small), and "small", (thumbnails).  If there was a max-mpixels version it would be a lot more usable for that.

The UI hitch when downloading is because TamperMonkey's GM_xmlhttpRequest implementation converts the data synchronously.  I need to use that call to download the image, since Pixiv doesn't have CORS set up to let it access its own images.  It would be a lot better if TM at least did that work in a worker.  I tried implementing that directly, but it seems like I can only access either the slowly converted arraybuffer, or the data interpreted as text...

I used the thumb strip at first, but it was always getting in the way (click-zoom near the edge, release to unzoom, and suddenly the manga strip flies open).  The manga view does preload all manga pages, but it only loads a couple at a time.  The preloading is less important now with the quick low-res preview and could probably be removed, and it'd just preload the next image.  I'll try that for a while and see if the slower loading gets annoying.

By the way, you can jump to the first/last page by pressing home/end.  I've played around with some context menu stuff to make this accessible with the mouse, but haven't found anything I like.

**Comment by ppixiv** [comment]
Images disappearing on zoom seems to be a compositing bug in newer versions of Firefox.  There's a different workaround for it in r63 that seems to work (wanted to avoid a timer since it's tricky to be sure there aren't race conditions).  88df826c40

**Comment by ppixiv** [comment]
Closing this to tidy up old tickets, I think most of this has been implemented in one way or another.
