### ISSUE TITLE
Feature request: Show Page Numbers on Image View

### ISSUE THREAD

**Issue by MarvNC** [ppixiv/ppixiv#25]
Currently, the page numbers are only shown on the illustration information hover box. I think it would be useful to show a page number display (e.g. "1/3") on the bottom or a corner of the page so you can know if there are more images in the gallery to scroll through without scrolling to a different gallery on accident.

**Comment by ppixiv** [comment]
Sorry for forgetting about this one.  I tried some ideas for saying "end of the post" when you reached the very end, but none of it worked very well.  I didn't want to put something onscreen since I don't want to put text over the image.

Other than the corner UI, you can also see the page number if you right-click, though.
