### ISSUE TITLE
Feature: Borders on thumbnails of followed users

### ISSUE THREAD

**Issue by analfetish69** [ppixiv/ppixiv#27]
Would it be possible to add a colored border to artwork thumbnails of your followed users? Kind of like how there is star on the tab icon for followed users. I follow a lot of people, and when browsing works through similar images, searches, or user bookmarks, it's hard to tell if a work is from from a followed user or not. If adding something like the heart icon for bookmarked works would be easier, that is fine as well. Ideally the user page of the followed user would be an exception to the thumbnail borders.

**Comment by ppixiv** [comment]
(Nice, er, name...)

Pixiv's API doesn't really let us do that, since search results don't include following info.  We have to look it up for each user one at a time, so it's only loaded on demand when viewing a post or showing the context menu.  The quickest way to check is to right-click a a search result and check the user thumbnail.

**Comment by analfetish69** [comment]
Well, it doesn't hurt to ask. Thanks for the reply and explanation!
