### ISSUE TITLE
Bug: Followed User Icon and Dropdown not showing

### ISSUE THREAD

**Issue by analfetish69** [ppixiv/ppixiv#32]
The eye icon (that indicates you are following someone), does not show up at all for me when I am on an artist's page or when I hold right click. The drop-down menu (that appears when you mouse over an artist's profile picture and allows you to follow someone) also does not appear for me, though if I am not following the artist, the folder drop-down box will still appear and allow me to follow them if I input something into it. If I am already following the artist, no drop-down will appear what-so-ever on mouse-over.

Very rarely the bug will go away for a small amount of time and functionality will be restored, but I'm not sure what the cause of this is. I've tested using ppixiv in both Brave and Firefox (that I keep up to date) to see if this was a browser issue, but I have the bug on both browsers. Usually I just deal with it and judge whether I'm following someone by the star icon for the tab, but even that star icon has gone away with the newest ppixiv update, and it just shows the official site icon for the tab now, not the ppixiv one.

Is there a place where I can get previous versions of ppixiv? I know I didn't have the bug with the r79 version, but some time after that, the bug started to infrequently appear and the frequency got worse and worse with every update, untill it's now rare to not see it. Sometimes the tag drop-down box would not appear as well, but the new tag drop-down fixed that. I can post an image of the drop-down not appearing, or only the folder box appearing, if you need me to.

**Comment by ppixiv** [comment]
I can't reproduce it on r119.  I tried in FF and Chrome on a couple test accounts.  Can you check a few things to try to get some clues?

- Are there any errors in the console?  (Not all errors are important, There are usually a couple random errors from Pixiv's scripts that can be ignored.)
- If you press Ctrl-F for a user you're already following, does it say "Already following this user"?
- If you press Ctrl-F to follow while on an artist page, does the followed icon appear?
- While on an artist page for a user you're following, can you run this command in the console and tell me the output:

    document.querySelector('.follow-container.big').className

It should say "follow-container widget big visible-widget followed" for a user you're following.

**Comment by analfetish69** [comment]
There was one error in the console.

DevTools failed to load source map: Could not load content for https://raw.githubusercontent.com/ppixiv/ppixiv/r119/output/main.scss.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE

It says "Already following this user" when pressing Ctrl-F for someone I follow.

The followed icon does not appear when pressing Ctrl-F on their page, but the "Followed ___" does appear.

It says "follow-container widget big visible-widget followed".

**Comment by ppixiv** [comment]
Hmm, it shows the folder input box in the dropdown but not the "follow"/"follow privately" buttons?  That's weird.  Try this, let let me know if you want more or less detailed instructions.  These are for Firefox since you mentioned you were using it.

- Open the artist page for a user you're following.
- Run:

document.querySelector('.follow-container.big .follow-buttons .unfollow-button')

- You should see: `<div class="follow-icon following-ic…ight popup popup-bottom" data-popup="Unfollow">`.  That's the unfollow button that's supposed to be visible.
- Reveal that in the inspector.  In Firefox, it's a weird star button to the right of <div...>.

Select the "Rules" tab and grab a screenshot (scroll to the top and press escape to get the console out of the way).  Here's a screenshot of mine so you know what to look for.  (Of course, look it over for any personal information that you don't want to include.  It doesn't know anything Pixiv doesn't, but your Pixiv ID might be in there somewhere.  You can also create a throwaway account and run it in incognito.)

![screenshot](https://user-images.githubusercontent.com/41404151/144164314-820efaf5-a003-4b4c-a0e5-321cf1aecbf0.png)

**Comment by analfetish69** [comment]
I figured out that the problem was uBlock Origin. I feel so stupid that I didn't check to disable that first. I apologize for taking up your time. I know that your time is valuable and I want to thank you for taking the time to help me out. Have a good day and keep up the good work.

**Comment by ppixiv** [comment]
Is it from a uBlock list?  Lots of people use that (myself included, but I haven't seen that), other people might run into it too if it's from a rule on a popular list.

**Comment by analfetish69** [comment]
I had "Parse and enforce cosmetic filters" checked, with "Ignore generic cosmetic filters" unchecked. Checking "Ignore generic cosmetic filters" fixed the problem. I got annoyed with the 'Do you accept that we use cookies?' messages and unchecked it a while back. It's weird that it only conflicted with ppixiv sometimes though.

**Comment by ppixiv** [comment]
Hmm, I have the same settings but I haven't seen that.  Can you check which rule it is?  You can see what's blocking things by opening the uBlock log window, and in "filter logger content" selecting "blocked".  It should show the rule that triggered, and clicking an entry will show which filter it's from.  Would be nice to know so I can try to avoid whatever the false positive is.

(I've adblocked dozens of those obnoxious cookie notices.  Good job, EU, staying on top of hot privacy issues of the 1990s)

**Comment by analfetish69** [comment]
Sorry for the late reply. It's part of the "Fanboy's Annoyance" and "Fanboy's Social" in the Annoyances category of the filter list. The filters are ##.follow-icon ##.follow-buttons ##.follow-button in the logger, and they only appear with "Ignore generic cosmetic filters" unchecked.

Also, I'm not sure if you are aware of this, but infinite scrolling no longer works for the similar artists page and it only shows 3 pictures per artist, rather than the previous 5.

And this is a more quality of life request, but would it be possible to add an option to allow preloading of images immediately upon clicking on an image that is part of a set like 1/x? And possibly an option to choose/increase the amount of images that are preloaded before stopping for slower internet speeds? 

With the new image loading feature, it's quite jarring to see an image suddenly come into focus, rather than the previous top-down receding black line. There's also no visual indicator for the image loading and I've often found myself waiting for an image to load, only to realize the image was blurry because of low resolution and not because it was still loading. Please bring back the black line of doom and feel free to disregard any of my suggestions/requests.

**Comment by ppixiv** [comment]
Hmm.  Doesn't seem like a great filter, those are strange class names to be blocking.  Good to know about it, though.

The loading was changed because the incremental loading made things really unresponsive when scrolling through high-res images.  Mousewheel scrolling through 3000x3000 images was pretty chunky before in Chrome, but decoding the images first fixes it.  Unfortunately there's sort of no in-between, browser APIs don't give access to show a progress bar or anything like that for image loading.  I'd rather not try to support both, because the image loading is a bit complex and having both incremental and preloading would be a pain.  I could have an option for some sort of "the image is still loading" indicator (like a loading spinner, but obviously something less in-your-face than a spinner in the middle of the screen), to make it more obvious when the image is finished loading, I'll think about it some more.

Similar artists uses the same API as Pixiv's "recommended users".  It always returns the same thing for the same user, it won't give more pages of results.  I've been updating search APIs to match what Pixiv's website does as they've been gradually updating features (the older ones eventually go away so things will break if I don't), that's probably part of that.  The non-artist-specific "recommended users" (the one in the main menu) doesn't have this limitation, though.  The work count per user was just set to 3 to match Pixiv, I raised it a bit in r120.

The preloading isn't too aggressive so it doesn't hammer the site if I load a 100-page manga post, but I'll take a look at it.
