### ISSUE TITLE
Works thumbnails are hidden on the bookmarks page if there are saved tags

### ISSUE THREAD

**Issue by DisasterInbound** [ppixiv/ppixiv#35]
Hello again,

It's late but happy new year.

I noticed the Bookmarks page is now not visible if there were tags previously saved. This happens even If I select All, Public or Private.

As you can see on the following screenshot the page is not fully shown because the tags list is always shown even if continue scrolling down:
![ChUzgt5vNYuuwTz9_2022-01-16_10-20-12](https://user-images.githubusercontent.com/64549167/149656006-85f84894-da5e-448a-a693-d7f663c98389.png)
 

Also I'm not sure if the following is caused by the same issue with the tags list but there is also a big gap at the beginning of the page before the first works are shown.

**Comment by ppixiv** [comment]
Hmm, I've never used bookmark tags that way.  I use them to organize bookmarks and I only have about 15 of them, so they fit comfortably at the top of the screen.  You're using them like post tags, I guess because Pixiv doesn't support searching post tags within bookmarks.

I think the fix is to switch to a dropdown if there are a lot of tags, like the "tags" dropdown on the artist page.  Real life is a bit busy at the moment, but I'll take a look at it when I get a chance.

**Comment by yul-oh895** [comment]
Thanks for the reply.

I did start using them as posts tags when i started using Pixiv several years ago but it became a hassle and stopped. Since i have near 2k booksmarks in this way i never bothered to update/remove those tags.

I guess this is what happens when a feature is not used properly lol

Don't worry, IRL is always first and take as much time is needed.

**Comment by ppixiv** [comment]
If you want to remove them, the batch tag editing stuff they added recently might help.  It'd still be tedious, but at least you'd only have to go through each tag and not every bookmark.

**Comment by ppixiv** [comment]
I've updated the bookmark page to put bookmark tags in a dropdown instead of at the top of the screen.  It's not perfect (there's no search so finding tags will be annoying if you have hundreds of them), but it should at least get the tags out of your way.

**Comment by DisasterInbound** [comment]
I forgot to reply to this, thanks for the update. The new dropdown button works perfectly to filter all tags.

I will still edit those bookmarks because the list is too long lol.

Thanks again.
