### ISSUE TITLE
Page goes blank when I click the floating P

### ISSUE THREAD

**Issue by yaomtc** [ppixiv/ppixiv#39]
When I click the Pixiv logo that appears near the bottom of any page after installing the userscript with Greasemonkey on Firefox, I get a blank white page.

Here is the HTML that appears when I "Inspect Element."

`<html class="" xmlns:wb="http://open.weibo.com/wb" lang="en"><head></head><body class="pixiv hide-r18g"></body></html>`

**Comment by ppixiv** [comment]
GreaseMonkey isn't currently supported, since it has bugs that are hard to work around.  There haven't been any real updates to it in ages, and TamperMonkey and ViolentMonkey are more actively maintained.

We should be logging a message and not activate with GreaseMonkey so it doesn't break things, but it looks like that's not working, I'll take a look at that.

**Comment by yaomtc** [comment]
Ah, it hasn't had *any* updates at all since January of last year. Thanks for pointing that out. I've now switched to Tampermonkey and it's working now!

**Comment by ppixiv** [comment]
The GreaseMonkey check is fixed in r128 (it just prints a message to the console).
