### ISSUE TITLE
[feature request] togglable(?) option for thumbnail-inner to show full image instead of a square

### ISSUE THREAD

**Issue by tybernation** [ppixiv/ppixiv#40]
hello! 
i was wondering if it was possible to make a setting, perhaps like a checkbox setting as the pan and zoom are, to make it so that the thumbnail-inner's are shown like [this image](https://files.catbox.moe/y3wtex.png) instead of like [this image](https://files.catbox.moe/zw0t1x.png). 
the way i've been doing it is in line 6654/6655, i've been changing the `width: \${max_width}px;` and `height: \${max_height}px;` to have both options be "unset"
this has been fine for the most part, every update reverts the code back of course, but i think it could be a cool feature.
 
a slight a bit of context for the next part, i usually will open images to new tabs so i can send links of images i like to a discord group. before the last update, whenever i'd open new tabs, it'd keep my position on the following/tag view page. but until i'd say the last update, whenever i open a new tab, it'd bring the page back up to the top. not sure what causes that but just thought i'd let you know in case you do end up wanting to add this.

thank you for maintaining this script!

**Comment by ppixiv** [comment]
It's a bit tricky, since it breaks content-intrinsic-size, which is used to optimize rendering large searches.  It needs to know the size of each entry in advance, and we might not know the thumbnail dimensions of everything in advance.  It'd probably need to try to fill it in, and disable content-visibility for the search if it's not available.  You might not notice this if you're in Firefox, I think it's only supported by Chrome.

What UI are you using to open tabs?  The page doesn't scroll if I middle-click search results.  Which browser?  (FYI, you can also copy a link from the image title in the top-left corner to get a link that works standalone.  That'll give you the same link you'd get if you opened a new tab.)

**Comment by tlombard2000** [comment]
ohhhh okay that's totally understandable for optimizational sake.

using the ppixiv ui if that's what you mean. if not, i'm unsure what you might mean. 
what i explained previously happens on firefox, i also tried it on edge/chrome/opera and it'd stop scrolling at a certain point on all of them with the height/width set to unset. as soon as i set it back to what it was originally, it'd go back to normal. 

also thank you for taking time for this probably minuscule issue that won't bother the general public

**Comment by ppixiv** [comment]
I mean, how are you opening tabs that's causing the view to scroll back up?  If you're middle-clicking to open something in a new tab, it shouldn't cause any scrolling in the tab you were on.

**Comment by tlombard2000** [comment]
both middle click or dragging the image to a new tab. then as soon as the new page loads, it'll shoot back up to the top. it's so weird but it never used to do this on previous versions

**Comment by ppixiv** [comment]
Are you still having the "scrolls up" problem?  I might be misunderstanding it, but I haven't seen anything like that.  You could try recording a video or a GIF showing what's happening.  (If you do I'd use the all-ages rankings page, and use a throwaway account in an incognito window so it doesn't contain any personal information.)

If it's not happening anymore or you don't want to spend time trying to figure it out, feel free to close the ticket.  I'm still wondering what it is, but I don't have any ideas right now...

**Comment by tlombard2000** [comment]
the scrolling up problem has stopped as of 144, however i've not tried it since around the time of posting this originally so the code is different from what it used to be. for example, the phrase "thumbnail-inner" from before does not exist. honestly i'm not sure what the heck the issue was before but i guess the code changing helped. i've been trying some stuff and now i've got it working now. 

unsure if that's anything you can comfortably implement, or something you'd want to add at all, but i'll add what i did just in case you're curious. the way i've made it working was changing 1718, 1719, and 1722 to "unset", and 1727 to "contain" [seen here](https://files.catbox.moe/hdpq0d.png). 
for edge (and i assume any chromium based browser), changing 1720 to "unset" was needed to make it work.

**Comment by ppixiv** [comment]
I did try playing around with variable-size thumbs, but it runs into problems.  If a page is loaded in the middle we only create thumbnails near the view, so it's quick if the search gives tons of results at once.  That means that thumbnails above the view don't exist until you scroll up (you can see the scroll bar changing height as this happens).

But if thumbnails have different widths, when thumbnails are added to the top they cause everything below them to shift around, so everything jumps around as you scroll up.  Normally this is avoided by always adding a whole column of images at a time (if there are 5 columns, we add 5 thumbs at a time), so images usually stay in the same column, but that needs each row to have the same number of images.

I could make thumbs fit in the thumbnail box, which looks different but does show the whole thumbnail without affecting anything else:

![temp](https://user-images.githubusercontent.com/41404151/175794119-540893d6-a04c-4055-9ee4-7badacc64f9c.png)

**Comment by tlombard2000** [comment]
ahh yeah i think i get what you mean, i've run into that. personally it doesn't bother me, but i can totally see the issue with that happening for others. definitely can be disorientating. 
even if it's not exactly the same, fitting the full into the thumbnail box is still totally cool, especially if it doesn't screw anything up. up to you if you would like to fully implement something like that ofc, i've just always liked the idea of being able to see the full image. thanks for all the help!

**Comment by ppixiv** [comment]
Try the aspect ratio thumbnail mode in r204.

**Comment by tybernation** [comment]
oh that's perfect, you're awesome. thank you so much!!!
