### ISSUE TITLE
Question about Firemonkey compatibility

### ISSUE THREAD

**Issue by Arias800** [ppixiv/ppixiv#48]
Hello,
I would like to use this userscript with Firemonkey, but I have multiple error.
This is the list of the error I got :
- The first one is TypeError: document.realCreateElement is not a function.
- The second one is a `TypeError: params.keys() is not iterable`.
It's trigger by this code :
```
    encodeHashParams(params)
    {
        let values = [];
        for(let key of params.keys())
        {
            let key_values = params.getAll(key);
            for(let value of key_values)
            {
                key = helpers.encodeHashParam(key);
                value = helpers.encodeHashParam(value);
                values.push(key + "=" + value);
            }
        }

        return values.join("&");
    },
```
And the last one is `Error: Permission denied to access property "body"` at every request done by the send_request function.

Do you think it is possible to make the script compatible with Firemonkey ? Or at least you have an idea of what is wrong with the send_request function ?

**Comment by ppixiv** [comment]
It looks like a bug in FireMonkey.  It defaults to "content" injection mode, which is incompatible with other script managers that all default to "page".  I can work around it by adding "inject-into page", but it's puzzling, since lots of scripts will be broken by this and I can't imagine he's not aware of the problem...

**Comment by ppixiv** [comment]
Try r149.

**Comment by Arias800** [comment]
Thank you, that work perfectly.
I will talk with the Firemonkey developer to know if he can fix this bug.

**Comment by ppixiv** [comment]
FYI, FireMonkey won't work in r161.  A change in TamperMonkey has made it difficult to support both TamperMonkey and FireMonkey, since the @inject-into flag needed for FireMonkey now breaks TamperMonkey.  I've brought up both issues: https://github.com/Tampermonkey/tampermonkey/issues/1602#issuecomment-1272632435 https://github.com/erosman/support/issues/429#issuecomment-1272636755

Hopefully this will be fixed (on both sides), but for now I recommend a different script manager.  If you don't like TamperMonkey, maybe try ViolentMonkey.  It's also open source, and has better compatibility than FireMonkey.
