### ISSUE TITLE
[Feature Request] Hotkeys for downloading, and copying image

### ISSUE THREAD

**Issue by The-Scout** [ppixiv/ppixiv#51]
It would be nice for there to be hotkeys for downloading, and copying the currently viewed image to clipboard, and downloading.

**Comment by ppixiv** [comment]
I've added Ctrl-S and Ctrl-Alt-S for saving images and manga.  It's not great, since Pixiv's server setup means (no CORS) we have to re-download the image even if you're saving an image that you're already viewing, which is why I haven't done much more with image saving since it was added.

Copying images to the clipboard has similar problems, I don't think it's possible to copy the image directly from the page into the clipboard without actually redownloading the file.  It's better to shift-right-click the image and use the browser's Copy Image from the context menu.

**Comment by The-Scout** [comment]
Thank you.
