### ISSUE TITLE
[Feature Requests] Support for more ranking combinations and fanbox links on image page

### ISSUE THREAD

**Issue by niZyalB** [ppixiv/ppixiv#52]
Hello, I've been using your tool for some days now and I really like it but I would like to suggest 2 things:

1. Ppixiv misses a lot of ranking category combinations like Male/Female+R18 or weekly+R18. On ppixiv you can only select one or the other, not both. You can in fact open the link https://www.pixiv.net/ranking.php?mode=male_r18 and add #ppixiv at the end and make it work. Although for some reason it doesn't take the "Hide work using these filters" on the top right on Pixiv into account and displays everything anyways. Is there a reason why it is like that?
3. I know there is a fanbox/fantia/booth link in the artist page, but it would be nice to have it on the particular Image page in the top left popup modal window as well.

**Comment by ppixiv** [comment]
I gave the rankings search another pass, try r182 and see if anything's missing.  It's a little tricky mapping the rankings combinations that actually exist to a UI.

The "hide work using these filters" doesn't work for me, I always assumed it was just a weirdly formatted label.  I see it if I load it in Firefox, but it doesn't do anything in Edge.  I think this is an old left-over filtering feature since it doesn't exist anywhere else.  I'd use mutes for content filtering instead, since it works everywhere.  They probably added this first before moving towards general tag and user mutes.

Showing the user links with the illust info would probably be overwhelming, since there can be a lot of them.  There are also quirks to getting some of those links, since it takes extra server calls to ask for Fanbox and Booth links.  I'm not sure why they do it that way.  You can get to these on the user page quickly from a search by right-clicking the thumbnail and double-clicking the avatar.

**Comment by niZyalB** [comment]
> I gave the rankings search another pass, try r182 and see if anything's missing.

Thanks, that was fast. I tried it out and it seems to cover all the combinations. I'm gonna try it out some more in the coming days.

> The "hide work using these filters" doesn't work for me, I always assumed it was just a weirdly formatted label. I see it if I load it in Firefox, but it doesn't do anything in Edge. I think this is an old left-over filtering feature since it doesn't exist anywhere else. I'd use mutes for content filtering instead, since it works everywhere. They probably added this first before moving towards general tag and user mutes.

The filter works for me on firefox (my main browser). It's not blocking every tag that fits the categories though. It's probably like you said, a legacy feature. I guess the filter system in ppixiv works better after setting it up.

> Showing the user links with the illust info would probably be overwhelming, since there can be a lot of them. There are also quirks to getting some of those links, since it takes extra server calls to ask for Fanbox and Booth links. I'm not sure why they do it that way. You can get to these on the user page quickly from a search by right-clicking the thumbnail and double-clicking the avatar.

I was thinking that since these links are already present on the pixiv illust page it might be easier. If it requires too many requests I guess it's not worth it.

**Comment by ppixiv** [comment]
Try r198.  I reworked the way these links are displayed by moving them to the avatar dropdown, merging it with the follow interface.  It was initially to make it work better for mobile, but it ended up being better overall (less of a "pile of buttons"), and you can access it from the avatar button in the popup menu and in the image info overlay now, since they're all the same button.  It avoids the problem of taking a few extra requests since it only loads it if you actually open the dropdown, so it won't spam the server if somebody mousewheels through a bunch of images while they happen to be hovering in the corner.

**Comment by niZyalB** [comment]
I know this is like giga late, but this isn't my main github account so I didn't notice your answer.
Those changes are fantastic I'm loving them, thanks (been using it for like almost a year now).
