### ISSUE TITLE
[Feature Suggestion] "All ages" filter on the New by Following page 

### ISSUE THREAD

**Issue by EeyoreDude** [ppixiv/ppixiv#56]
The new by following page can be filtered to show only R-18 or show everything. I would love to be able to filter out R-18 images on this page (like how it can be done on other pages, i.e. the search page).

**Comment by ppixiv** [comment]
I'd like that too, actually, but for some reason that's the only filter Pixiv offers for that search.  (It seems a bit backwards to me...)  I've been hesitant to add client-side filters to searches, since I want to make sure that (for example) if you're following mostly R-18 artists and you hide R-18 works, it doesn't end up loading 100 pages trying to fill the screen, and stops and asks the user at some point.  It's solvable, I just haven't spent the time to figure out a good way to do it.  A halfway solution that doesn't have that problem would be a way to display them as muted images, where you'd still have to scroll past them.

You could also enable the R-18 filter in your account settings.  I haven't tried that recently, and of course that's a pain if you switch back and forth or want different content in different windows, but it's another option.

**Comment by EeyoreDude** [comment]
Interesting. It had crossed my mind that Pixiv was the limiter but I dismissed it as ridiculous, guess I underestimated them lol.

Appreciate the quick feedback, keep up the great work!
