### ISSUE TITLE
[Feature Request] Option to preload all images in manga pages right away

### ISSUE THREAD

**Issue by Rhodan81** [ppixiv/ppixiv#75]
Love the script and appreciate the work you do here.

I have a reuqest and was wondering if it's possible to do this.
When I use ppixiv I usually open alot of tabs with illustrations I want to see from the "New works by following page", then go through them one by one.
When I open an illustrations that way that has manga pages, it only loads the full quality version of the first image. The remaining images seem to only load once I start flicking through the pages. Before they are fully loaded I get to see a low quality version of the image that then switches to the high quality version after a second or two.

I get that this might be by design to keep things efficient, but it would be nice to have an option that we could enable, that causese ppixiv to preload all the full quality version images of a manga illutration, since I almsot always view every single one of those images. Waiting for the images to load especially when flicking through them fast can be a bit annoying, considering that there's usally plenty of time for the script to preoad everything (By the time I get to the tab, time serveral minutes or more might have passed). Preloading everything would greatly improve the viewing experince for me.

**Comment by ppixiv** [comment]
It's actually a bug that it isn't loading manga pages, but I'm a little hesitant to turn it on as is and have it load the entire thing.  Pixiv has grumbled a bit about scrapers recently, and I don't want to be too aggressive with preloading and get people incorrectly flagged as bots.

Try r224.  I've fixed it and added a small delay for pages that are further out.  If you're on page 10 it'll load pages 8-12 quickly, but wait a second or two between pages further away.  That way it'll load pages at a rate similar to a user scrolling quickly instead of loading a huge 200 page post all at once, but it'll still finish on its own.

**Comment by Rhodan81** [comment]
This works great. Thank you!
