### ISSUE TITLE
[Feature Request] Filter for bookmarks on search & Default image fitting

### ISSUE THREAD

**Issue by EeyoreDude** [ppixiv/ppixiv#77]
Loving the script as always.

I think it would be sweet if I could filter the search page to only show images I've bookmarked (or to add a tag searching feature to the bookmarks page that's separate from my personally added bookmark tags). Often times I know the image I'm looking for but can't find it without scrolling through 1000s of images on my bookmarks until I find it.

Not sure how feasible this would be to implement since Pixiv doesn't seem to innately have any similar functionality, but it sure would be nice if it could work.

--

I also think it would be great to have an option for images to be fit to the screen both horizontally and vertically when I initially view them. I mostly have issues with landscape images on my phone screen, where they start very zoomed in on the center of the image. Even if I double tap to zoom out, after swiping to the next image the view is reset back to the default fit.

**Comment by ppixiv** [comment]
Sorry, didn't see this (maybe something wrong with my GH notifications...).  Doing client-side searches like that doesn't really work well, since it could need to make hundreds of API calls to load bookmarks, and I don't want people getting themselves blocked from the site from hammering the API.  I've thought about ways to auto-detect if we're loading too much at once and having it stop and say "click here to keep looking", so it doesn't autopilot and make a ton of requests without the user noticing, but it might be more of a hassle than it's worth.

I've tried making it remember the last zoom on mobile.  It'll remember cover and fit (normal zoomed in and zoomed out) but not other zoom levels.  That's to make sure it's easy to get it to stay on either of those two, since there aren't separate zoom level buttons like there are on desktop.  This isn't in a release yet, some stuff that needs more testing first.

**Comment by ppixiv** [comment]
Try r229 for the zoom update.
