### ISSUE TITLE
[Feature Request] Allow Dragging Images Outside the Window

### ISSUE THREAD

**Issue by DT3264** [ppixiv/ppixiv#80]
I use to download pixiv images by manually clicking and drawing, the script is awesome, but I don't want to zoom when I click and drag an illustration on the single illustration view, it would be nice to be able to, like, enable draging by having CTRL pressed so it does not clash with something else.

I'd do the change myself but after playing with the code for a while I could not archieve what I wanted at least at the script level but the following code in the console worked
```
// Quick hack to remove all listeners of an object by cloning it
// Removes the click handler, thus allowing to drag images out the window
const oldElement = document.getElementsByClassName("viewer-images")[0];
const newElement = oldElement .cloneNode(true);
oldElement .parentNode.replaceChild(newElement, oldElement );
```

**Comment by ppixiv** [comment]
Would Shift work instead?  Ctrl clashes with the "hold ctrl to open popup menu" setting, and shift-left-click is consistent with shift-right-click to open the browser context menu.  Either way I have to ctrl-shift-drag to trigger a save, at least in Windows with Chrome.  (With FF I have to shift-alt-drag, but it doesn't work in FF anyway since it refetches the image without a referrer and saves a 403 error instead.)

**Comment by DT3264** [comment]
Using shift instead ctrl sounds good, I updated #81 to use shift.

And, as far as I saw, once you start dragging the image is safe to release any key since some key combinations trigger events that do not allow to manipulate the dragged file (like copying with Ctrl).

One thing that's interesting, as far as I understand, you mention on FF doesn't work, I don't know if it is expected or unexpected, but on my FF session it works with no issues.

**Comment by ppixiv** [comment]
It seems to work if it's on CloudFlare but not when loading from Pixiv directly.  CF returns images from its cache even though the referer is different.  Chrome works either way since it just saves the image it already has cached instead of downloading it again.  Just watch out since it doesn't show an error, and if you don't notice you'd end up with a directory full of text files with .png filenames...
