### ISSUE TITLE
Bookmark image without like?

### ISSUE THREAD

**Issue by u3shit** [ppixiv/ppixiv#89]
It looks like if I bookmark an image from ppixiv, it automatically adds a like too, which is pretty annoying, since a far as I know you can't undo it. Would it be possible for the bookmark button to just bookmark, not also like?

**Comment by ppixiv** [comment]
What's the reason to want to bookmark without liking?  They're both a just vague "number of people who like this illustration" number to the artist, and the Pixiv mobile app also merges them.  From what I can tell Pixiv doesn't actually keep track of who liked an image other than a 24-hour memory to prevent re-liking an image immediately (which is why you can re-like an image again every day, and why you can view people's bookmarks but not their likes).  It's just incrementing a counter.

(Liking an image without bookmarking it can make sense, if you like a lot of an artist's posts and want to +1 a lot of them but don't need all of them in your bookmarks, but in practice the like number is pretty meaningless with the way Pixiv has them implemented.)

**Comment by ppixiv** [comment]
Likes aren't reset, but as far as I can tell Pixiv doesn't remember that *you* specifically liked an image after about a day.  If you try to like an image twice in a row it'll say "already liked", but you can come back the next day and like it again and it'll add another like to the counter.  From what I can tell likes are just a number on the image, it's not a registry of who likes an image.  That's different from bookmarks, where it remembers each bookmark individually.  I think this is fundamentally why you can't "un-like" an image, after a day has passed it doesn't even know that you liked it anymore.  I think likes also don't affect recommendations but bookmarks do (from looking at the API data, it has tags for recommendations based on bookmarks, but not likes).

I think the ~50% like ratio to bookmarks is exactly because the mobile app auto-likes images when you bookmark, but the website doesn't.  So all bookmarks on mobile are also likes, but on desktop people probably mostly just bookmark, giving the around 50% ratio.  (It's not a very well thought out system...)

**Comment by ppixiv** [comment]
I used to be annoyed by not being able to undo likes, but I eventually got a better understanding of what was actually happening.   They're not tracking likes per user, only keeping a short-term (24 hours, it seems) cache to prevent spamming them--it's really just a count on the image.  I don't think the system is well thought out, but a like on Pixiv is really nothing more than a "+1 This Was Interesting Somehow" counter, and I think it makes sense to follow the lead of their mobile apps in pretending they don't exist and just triggering a like on bookmark.  I don't want to bloat settings with options I can't see a use case for--I don't see any case where I'd bookmark an image, but not want to say "cool, that was interesting somehow".  Let's keep things simple where we can.
