### ISSUE TITLE
[Feature Request (Mobile)] Double tap to bookmark on mobile

### ISSUE THREAD

**Issue by EeyoreDude** [ppixiv/ppixiv#92]
I was wondering if it would be possible to add a double-tap-to-bookmark shortcut on mobile. It could just default to public bookmark.
If not that, then perhaps an option for the heart to bookmark publicly and long press for private?

I know its quite nit picky, but I find needing two actions to bookmark an image gets a little tedious, anything that could fix that would be awesome.

Incredible script as always, great work.

**Comment by ppixiv** [comment]
A double tap would need to delay opening the tag menu on tap to give a chance to double-tap, which would make it feel unresponsive.  It could be done with an alternative UI, like tap and drag up to open a small submenu (so it could be activated in one motion), but that's more involved since I don't have any UI like that right now.  I'll think about it some more.  Personally I tag all of my bookmarks, so that's why it's optimized around opening the tag list...

By the way, which script manager do you use?  The iOS one I was using (Stay) just updated and abruptly turned to garbage (suddenly it's requiring a WeChat login to use it--really fishy), and all the other ones I've found ("Userscripts" and "Addons", I'm surprised these names were even allowed) are pretty broken.  It looks like there's a version of Tampermonkey on Android, but not on iOS...

**Comment by EeyoreDude** [comment]
I used a throwaway email to make a Stay account because the other options are so bad lol.

Valid points on the double tap.
