### ISSUE TITLE
how can i remove blank images after i muted pixiv account. so that pixiv does not load 1000 pages of blank images.

### ISSUE THREAD

**Issue by aurimilky** [ppixiv/ppixiv#98]
so i then came across your script. which i been having fun using.

got a question about muting pixiv accounts using your script. i can see that it removes the image that are mute and leave a blank image. is there a way to also remove blank images. so that  pixiv does not load over 1000 pages of blank images?

if not then can this please been added?

many thanks
ashton

**Comment by ppixiv** [comment]
It's tricky.  The problem is that if you have that many muted images, it would have to load tons of pages to fill up the screen.  If it takes 5 pages of "real" pages to finish filling one screen, it'd be spamming tons of requests to Pixiv.  We already send requests faster than Pixiv normally would, I don't want it to cause problems or get people blocked.

**Comment by aurimilky** [comment]
okay no problem. 

so it cannot be do client side? by 1000 pages i mean not loading all 1000 pages at onces. i mean remove each black image on each page then it loads up.

oh i came this script before it came across you script but i was not able to get it to work. it another script for mute pixiv accounts using uBlockOrigin.

https://www.reddit.com/r/uBlockOrigin/comments/f76a7j/using_ublock_to_mute_multiple_accounts_on_pixiv/

**Comment by aurimilky** [comment]
oh also does mute in your script work client side or server side?

**Comment by ppixiv** [comment]
Pixiv's mutes are client-side, the APIs ignore them (or at least many of them do, they're not too consistent) and they filter them out in the UI.  It's not a big deal for Pixiv since they're paginated, but it's more of a problem for an auto-loader.

An example of a pathologically bad case would be if you muted "dogs" and then searched for "dogs".  If the UI didn't have some safeties in place, it could sit there endlessly loading pages forever, since they'd all get filtered out and it would always need more data.  It's a general problem for client-side filtering.

**Comment by aurimilky** [comment]
oh ok cool. also how do set your script to use page numbers instead of continuous scrolling?

**Comment by ppixiv** [comment]
The scroller is core to the way the UI works, there's no pagination.  It does remember which page you're on in the results (you can see it updating in the URL), so if you're on page 200 of a long search, it'll pick up from the same place if the page is reloaded.
